generatorName: python
outputDir: samples/openapi3/client/petstore/python-asyncio
inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/python
library: asyncio
additionalProperties:
  packageName: petstore_api
  useOneOfDiscriminatorLookup: "true"
  disallowAdditionalPropertiesIfNotPresent: false
  mapNumberTo: StrictFloat
